name: camping_game_show
description: "Application de jeu interactif pour les campings."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.16.4"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.0
  firebase_database: ^10.5.0
  cloud_firestore: ^4.17.0
  firebase_storage: ^11.7.0
  firebase_crashlytics: ^3.5.0
  flutter_bloc: ^8.1.4
  riverpod: ^2.4.0
  flutter_riverpod: ^2.4.0
  go_router: ^13.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^8.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.3
  connectivity_plus: ^5.0.2
  video_player: ^2.8.1
  cached_network_image: ^3.3.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.5
  intl: ^0.19.0
  path_provider: ^2.1.1
  uuid: ^4.2.1
  crypto: ^3.0.3
  logger: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  freezed: ^2.4.7
  json_serializable: ^6.7.2
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/backgrounds/
    - assets/images/illustrations/
    - assets/videos/
    - assets/fonts/
  
  fonts:
    - family: Futura
      fonts:
        - asset: assets/fonts/Futura-Bold.ttf
          weight: 700
        - asset: assets/fonts/Futura Medium.TTF
          weight: 500
        - asset: assets/fonts/Futura-Book.ttf
          weight: 400
    - family: Horatio D
      fonts:
        - asset: assets/fonts/Horatio D Bold.otf
          weight: 700
        - asset: assets/fonts/Horatio D Light Regular.otf
          weight: 300
    - family: HoratioDMed
      fonts:
        - asset: assets/fonts/HoratioDMed.ttf
          weight: 500
